# Generated by Django 5.0.8 on 2026-06-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Police', 'Police'), ('Ambulance', 'Ambulance'), ('Fire Brigade', 'Fire Brigade'), ('Women Helpline', 'Women Helpline'), ('Child Helpline', 'Child Helpline'), ('Blood Bank', 'Blood Bank'), ('Hospital', 'Hospital'), ('Mental Health', 'Mental Health')], max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
